<?php
// config.php — basic configuration for the mock Bincoin pool
define('POOL_NAME', 'Bincoin Mining Pool');
define('COIN_TICKER', 'BNC'); // 
define('REFRESH_SECONDS', 5);

// File paths for JSON data (generated by the Python script)
define('DATA_DIR', __DIR__ . '/data');
define('STATUS_FILE', DATA_DIR . '/status.json');
define('BLOCKS_FILE', DATA_DIR . '/blocks.json');
define('WORKERS_FILE', DATA_DIR . '/workers.json');
?>